resources:
- repo: self

queue:
  name: Hosted VS2017
  demands: npm

steps:
- task: Npm@1
  displayName: npm install
  inputs:
    verbose: false

- task: Npm@1
  displayName: npm run build
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: CopyFiles@2
  displayName: Copy infrastructure
  inputs:
    SourceFolder: infrastructure
    TargetFolder: '$(build.artifactstagingdirectory)/iac'

- task: CopyFiles@2
  displayName: Copy site
  inputs:
    SourceFolder: build
    TargetFolder: '$(build.artifactstagingdirectory)/site'

- task: PublishBuildArtifacts@1
  displayName: Infrastructure
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/iac'
    ArtifactName: iac

- task: PublishBuildArtifacts@1
  displayName: Site
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/site'